theme: jekyll-theme-minimal

# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
#url: "http://m-clark.github.io"
#baseurl: ""

# If you are building a GitHub project page then use these settings:
url: "http://dylanfsun.github.io/biostat699-project2"
baseurl: "/biostat699-project2"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: Project 2

# Short description of your site
description: Various stuff regarding stats and related
